# Generated by Django 3.2.5 on 2021-07-29 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDjangoDB', '0002_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlunosBSI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('periodoIngresso', models.CharField(max_length=100, verbose_name='Período de Ingresso')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Nota - Web Avançado')),
                ('situacao', models.CharField(max_length=100, verbose_name='Situação')),
            ],
        ),
    ]
